
{{ config(materialized='view') }}

select
    TRANSACTION_ID,
    ACCOUNT_NUMBER,
    TO_TIMESTAMP_NTZ(TRANSACTION_DATE) as TRANSACTION_DATE,
    TRANSACTION_AMOUNT,
    INITCAP(TRIM(MERCHANT_NAME)) AS MERCHANT_NAME,
    INITCAP(TRIM(TRANSACTION_TYPE)) as TRANSACTION_TYPE,
    INITCAP(TRIM(CATEGORY)) as CATEGORY,
    INITCAP(TRIM(CITY)) as CITY,
    INITCAP(TRIM(PAYMENT_METHOD)) as PAYMENT_METHOD,
    CUSTOMER_AGE,
    INITCAP(TRIM(CUSTOMER_GENDER)) as CUSTOMER_GENDER,
    UPPER(SUBSTR(TRIM(CUSTOMER_OCCUPATION),1,1)) || LOWER(SUBSTR(TRIM(CUSTOMER_OCCUPATION),2)) as CUSTOMER_OCCUPATION,
    CUSTOMER_INCOME,
    ACCOUNT_BALANCE,
    case when upper(TRANSACTION_STATUS) = 'SUCCESS' then 1 else 0 end as TRANSACTION_STATUS,
    case when upper(FRAUD_FLAG) = 'YES' then 1 else 0 end as FRAUD_FLAG,
    case when upper(DISCOUNT_APPLIED) = 'TRUE' then 1 else 0 end as DISCOUNT_APPLIED,
    LOYALTY_POINTS_EARNED
from {{ source('raw_data', 'BANKING_TRANSACTIONS') }}
